// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBag9uY10b44sxVCfjnZdMrjB9t1M1zGFA',
    appId: '1:414624461790:web:3ae5469f90d2347e6fa34f',
    messagingSenderId: '414624461790',
    projectId: 'color-fit1',
    authDomain: 'color-fit1.firebaseapp.com',
    storageBucket: 'color-fit1.appspot.com',
    measurementId: 'G-NL1SWR6LX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmgt6hOQezuxRhDKloZHCwUIr6WG20dM',
    appId: '1:414624461790:android:95d6eeaf97c240276fa34f',
    messagingSenderId: '414624461790',
    projectId: 'color-fit1',
    storageBucket: 'color-fit1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXl2SzsWcp50oq6u2fsq7NWIxgtKMptQ',
    appId: '1:414624461790:ios:41405b3130d63d926fa34f',
    messagingSenderId: '414624461790',
    projectId: 'color-fit1',
    storageBucket: 'color-fit1.appspot.com',
    iosBundleId: 'com.example.colorFit1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBag9uY10b44sxVCfjnZdMrjB9t1M1zGFA',
    appId: '1:414624461790:web:074db898ea728d466fa34f',
    messagingSenderId: '414624461790',
    projectId: 'color-fit1',
    authDomain: 'color-fit1.firebaseapp.com',
    storageBucket: 'color-fit1.appspot.com',
    measurementId: 'G-M0R4GKVW9N',
  );
}
